export default function () {
  return {
    background: 'road',
    blackMask: 'transitionBackground',
    timeout: 8,
    itemChance: 7,
    textInfo: {
      textStage: 'STAGE 3 ROAD',
      startText: 'START !!',
      endStage: 'STAGE 3 SUCCESS !!',
      gameOver: 'GAME OVER !!',
      y: 100,
      style: {
        font: '60px Karmatic Arcade',
        strokeThickness: 1,
        stroke: '#210474',
        fill: '#ffffff',
      },
    },
    bloodArea: {
      x: 0,
      y: 0,
      spriteName: 'blood',
    },
    hearts: {
      totalLifes: 8,
      x: 20,
      y: 20,
      offset: 40,
      spriteSheet: 'hearts',
      frameName: 'heart-on',
    },
    explosion: {
      x: -1000,
      y: -1000,
      spriteSheet: 'explosion',
      frameName: null,
    },
    guy: {
      x: -80,
      y: 152,
      offsetX: 100,
      spriteSheet: 'scavenger',
      frameName: 'scavenger4',
    },
    zombies: [{
      x: 1820,
      y: 250,
      time: 2000,
      animation: 'rightIdle',
      spriteSheet: 'zombie',
      frameName: 'Zombie1',
      tween: {
        offsetY: 96,
        x: 1520,
      },
    }],
    platforms: [{
      x: -250,
      y: 250,
      isTweenable: false,
      scaleX: 1,
      scaleY: 1,
      spriteSheet: 'platforms',
      frame: 'Platform1',
    }, {
      x: 400,
      y: 500,
      isTweenable: true,
      velocity: 1350,
      scaleX: 1,
      scaleY: 1,
      spriteSheet: 'platforms',
      frame: 'Platform3',
    }, {
      x: 650,
      y: 750,
      isTweenable: true,
      velocity: 1700,
      scaleX: 1,
      scaleY: 1,
      spriteSheet: 'platforms',
      frame: 'Platform3',
    }, {
      x: 900,
      y: 500,
      isTweenable: true,
      velocity: 750,
      scaleX: 1,
      scaleY: 1,
      spriteSheet: 'platforms',
      frame: 'Platform3',
    }, {
      x: 1250,
      y: 500,
      isTweenable: true,
      velocity: 500,
      scaleX: 1,
      scaleY: 1,
      spriteSheet: 'platforms',
      frame: 'Platform3',
    }, {
      x: 1500,
      y: 250,
      isTweenable: false,
      scaleX: 1,
      scaleY: 1,
      spriteSheet: 'platforms',
      frame: 'Platform1',
    }],
  };
}
